### ISSUE TITLE
Default `plot.add(line: "raw")` instead of `"linear"`

### ISSUE THREAD

**Issue by jamesrswift** [cetz-package/cetz-plot#22]
https://github.com/cetz-package/cetz-plot/blob/8a5f0658b4dea5a889f7ce096e38b6f38bd81b22/src/plot/line.typ#L220

I think people will naturally expect the function being plotted to have its points filtered if its linear (been chasing my tail because of this because of logarithmic plots of linear functions)

**Comment by johannes-wolf** [comment]
Is there a visible difference if you change it to `"raw"`? The reason of `"linear"` is to have fewer points if lines are straight, which can improve rendering speed of PDF & SVGs a lot! There must be _no visible_ difference between the two modes.

**Comment by JamesxX** [comment]
linear: 
![image](https://github.com/user-attachments/assets/8dc7adff-31b4-4751-8164-b506b60c2c94)

![image](https://github.com/user-attachments/assets/46dc6698-cf64-4f12-800b-1d6ce1571848)

**Comment by johannes-wolf** [comment]
The error here is, that the linearization/optimization is done on the source data, which is not good. Goal: optimize the generated line-segments.

**Comment by johannes-wolf** [comment]
Fixed on master. The default ist `raw`.
