### ISSUE TITLE
Feature Request: logarithmic scale in plot

### ISSUE THREAD

**Issue by konradmoesch** [cetz-package/cetz-plot#3]
I would like to use a logarithmic x-axis in a cetz plot.
One example for a usage is bode plots, where the frequency (x-axis) is normally plotted logarithmically (10^(-3) to 10^3):
![image](https://github.com/cetz-package/cetz/assets/15964885/3f0f6641-6045-47e0-a189-884fb68055d3)
But it would also be useful for the y-axis, I think.
TikZ supports this via `xmode=log`, for example, but maybe `x-tick-step` could be extended for log scaling.

**Comment by JamesxX** [comment]
Made a draft PR for my attempt here: #15. Input welcome

**Comment by JamesxX** [comment]
![image](https://github.com/user-attachments/assets/2028d272-37fe-4718-b94c-1dac8c17ebfa)

**Comment by JamesxX** [comment]
Should be closed by #21
