### ISSUE TITLE
cetz-plot not in typst universe

### ISSUE THREAD

**Issue by cskeeters** [cetz-package/cetz-plot#38]
`README.md` suggests that you need to use:

    #import "@preview/cetz-plot:0.1.0": plot, chart

to use cetz-plot, but it's not in the [typst universe](https://typst.app/universe/).  Compiling a document with the suggested syntax results in the error:

    error: package not found (searched for @preview/cetz-plot:0.1.0)

Removing the import producing a working plot.  Has cetz-plot been incorporated into cetz?  Does `README.md` need to be updated to reflect that?

**Comment by johannes-wolf** [comment]
It's the other way around. cetz-plot has been moved out of cetz. The current version of cetz (0.2.2) contains the plotting functionality; the next version will not.

I will add a line to the readme, that cetz-plot has not yet been released.

**Comment by cskeeters** [comment]
Dang, you're on top of it!  Much appreciated.

**Comment by chpaxson** [comment]
Hello, now that cetz 0.3.0 has been released, will cetz-plot be added to the typst universe?

**Comment by johannes-wolf** [comment]
> Hello, now that cetz 0.3.0 has been released, will cetz-plot be added to the typst universe?

I am planning to publish it on universe in the next days.
