### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by adrfantini** [cetz-package/cetz-plot#55]
When using `cetz-plot` following the README, I am getting:
```
error: package not found (searched for @preview/cetz-plot:0.1.0)
  ┌─ docs/typst/plots.typ:4:8
  │
4 │ #import "@preview/cetz-plot:0.1.0": plot
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred while importing this module
```
The complete import statement is:
```
#import "@preview/cetz:0.3.0"
#import "@preview/cetz-plot:0.1.0": plot
```

The package cannot be found on the Typst universe website either.

A temporary workaround is to install it manually, but it's not great.

**Comment by johannes-wolf** [comment]
Yes, `cetz-plot` is not on typst universe right now, sorry. I will try to create a PR this weekend.

**Comment by johannes-wolf** [comment]
The PR to include it on universe is now open.

**Comment by adrfantini** [comment]
Thanks!

Link for those who want to check out when it's merged: https://github.com/typst/packages/pull/1118
