### ISSUE TITLE
piechart labels result in extra boxes

### ISSUE THREAD

**Issue by Tetragramm** [cetz-package/cetz-plot#62]
Adding labels to a piechart cause a lot of extra things to be drawn. Specifically a box and the label are drawn for each slice below the chart.

```
#import "@preview/cetz:0.3.1"
#import "@preview/cetz-plot:0.1.0"
#cetz.canvas(length: 50%, {
  import cetz.draw: *
  import cetz-plot: *
  chart.piechart(
    ((value: 1, label: ""), (value: 1, label: [#text(stroke: green)[Here's a Label]])),
    value-key: "value",
    label-key: "label",
    // ((1, []),
    //  (1, [Here's a Label]),
    // ),
    // value-key: 0,
    // label-key: 1,
    radius: 0.5,
    outer-label: (content: none),
    inner-label: (content: "LABEL", radius: 130%),
    slice-style: ((fill: blue, stroke: red),),
  )
})
```
![image](https://github.com/user-attachments/assets/20ae439c-959d-426b-89c2-bc84430eb93e)

**Comment by johannes-wolf** [comment]
It is the legend, that gets shown as long as one element has a label. You can disable it by setting `legend: (label: none)`.

**Comment by Tetragramm** [comment]
Ah, I see. Thank you for your answer.

May I make a suggestion?  In the manual, put a list of breaking changes.  I was reading the entry for piechart, but I was focusing on label and style elements, skipping right over the legend option, since I wasn't using it.
