### ISSUE TITLE
Annotation domain always includes the origin

### ISSUE THREAD

**Issue by jamesrswift** [cetz-package/cetz-plot#72]
MRE:
```typ
#test-case({
  import draw: *
  set-style(rect: (stroke: none))

  plot.plot(size: (6, 4), {
    plot.add(domain: (100, 101), calc.sin)
    plot.annotate(padding: .1, {
      content( (101.5, 0), [A])
    })
  })
})
```

outputs:

![image](https://github.com/user-attachments/assets/12ea4668-90e7-484a-a48a-c1054f8cb510)

**Comment by jamesrswift** [comment]
Stumbled into some more annotation shenaniganry - there's no conversion between canvas units (when measuring width and height) and plot units

**Comment by johannes-wolf** [comment]
We cannot really fix annotations rn. We need cetz' custom coordinate support to correctly do that. The `annotate` function is completely broken.
